// <auto-generated />
using System;
using Frank.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FrankApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Frank.Domain.Entities.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnswerText")
                        .HasColumnType("text")
                        .HasColumnName("answer_text");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_id");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_text");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("session_type");

                    b.Property<string>("TapValue")
                        .HasColumnType("text")
                        .HasColumnName("tap_value");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserId", "QuestionId");

                    b.HasIndex("UserId", "SessionId");

                    b.ToTable("answers", (string)null);
                });

            modelBuilder.Entity("Frank.Domain.Entities.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("app_settings", (string)null);
                });

            modelBuilder.Entity("Frank.Domain.Entities.ChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Completed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("completed");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("session_type");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date", "SessionType");

                    b.ToTable("chat_sessions", (string)null);
                });

            modelBuilder.Entity("Frank.Domain.Entities.ConversationHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("CrisisFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("crisis_flag");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("session_type");

                    b.Property<string>("TapValue")
                        .HasColumnType("text")
                        .HasColumnName("tap_value");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserId", "Date");

                    b.ToTable("conversation_history", (string)null);
                });

            modelBuilder.Entity("Frank.Domain.Entities.EveningCheckin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("DayResult")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("day_result");

                    b.Property<string>("HardEnvironment")
                        .HasColumnType("text")
                        .HasColumnName("hard_environment");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string[]>("SlipType")
                        .HasColumnType("text[]")
                        .HasColumnName("slip_type");

                    b.Property<string>("TomorrowRisk")
                        .HasColumnType("text")
                        .HasColumnName("tomorrow_risk");

                    b.Property<bool>("UsedUrgeButton")
                        .HasColumnType("boolean")
                        .HasColumnName("used_urge_button");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserId", "Date")
                        .IsUnique();

                    b.ToTable("evening_checkins", (string)null);
                });

            modelBuilder.Entity("Frank.Domain.Entities.MiniMirrorEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("observation");

                    b.Property<bool>("Opened")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("opened");

                    b.Property<string>("QuotesShown")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("quotes_shown");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("triggered_at");

                    b.Property<int>("UrgeCount")
                        .HasColumnType("integer")
                        .HasColumnName("urge_count");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("mini_mirror_events", (string)null);
                });

            modelBuilder.Entity("Frank.Domain.Entities.MorningCheckin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("ForecastText")
                        .HasColumnType("text")
                        .HasColumnName("forecast_text");

                    b.Property<bool>("HighRiskFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("high_risk_flag");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int?>("YesterdayScore")
                        .HasColumnType("integer")
                        .HasColumnName("yesterday_score");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserId", "Date")
                        .IsUnique();

                    b.ToTable("morning_checkins", (string)null);
                });

            modelBuilder.Entity("Frank.Domain.Entities.NotificationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("LinkedId")
                        .HasColumnType("text")
                        .HasColumnName("linked_id");

                    b.Property<bool>("Opened")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("opened");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date");

                    b.ToTable("notification_log", (string)null);
                });

            modelBuilder.Entity("Frank.Domain.Entities.PreUrgeVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("onboarding")
                        .HasColumnName("source");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("VersionNum")
                        .HasColumnType("integer")
                        .HasColumnName("version_num");

                    b.Property<string>("VersionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version_text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("pre_urge_versions", (string)null);
                });

            modelBuilder.Entity("Frank.Domain.Entities.Question", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("Conditions")
                        .HasColumnType("jsonb")
                        .HasColumnName("conditions");

                    b.Property<string>("Frame")
                        .HasColumnType("text")
                        .HasColumnName("frame");

                    b.Property<string>("InputType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("input_type");

                    b.Property<string[]>("PatternTags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("pattern_tags");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("mvp")
                        .HasColumnName("phase");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("session_type");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<int>("Weight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("Frank.Domain.Entities.QuestionSelectionRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("Conditions")
                        .HasColumnType("jsonb")
                        .HasColumnName("conditions");

                    b.Property<string>("Frame")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("frame");

                    b.Property<bool>("Required")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("required");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rule_name");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("session_type");

                    b.Property<int>("Slot")
                        .HasColumnType("integer")
                        .HasColumnName("slot");

                    b.HasKey("Id");

                    b.ToTable("question_selection_rules", (string)null);
                });

            modelBuilder.Entity("Frank.Domain.Entities.QuestionUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_id");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("session_type");

                    b.Property<DateTime>("ShownAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("shown_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId", "QuestionId", "ShownAt");

                    b.ToTable("question_usage", (string)null);
                });

            modelBuilder.Entity("Frank.Domain.Entities.TapOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("ColorHint")
                        .HasColumnType("text")
                        .HasColumnName("color_hint");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<string>("PatternTag")
                        .HasColumnType("text")
                        .HasColumnName("pattern_tag");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("tap_options", (string)null);
                });

            modelBuilder.Entity("Frank.Domain.Entities.UrgeEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddictionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("addiction_type");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<string>("Environment")
                        .HasColumnType("text")
                        .HasColumnName("environment");

                    b.Property<string>("HaltRoot")
                        .HasColumnType("text")
                        .HasColumnName("halt_root");

                    b.Property<string>("InterventionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("intervention_id");

                    b.Property<string>("MoodValence")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mood_valence");

                    b.Property<string>("PostUrgeMood")
                        .HasColumnType("text")
                        .HasColumnName("post_urge_mood");

                    b.Property<bool>("Resisted")
                        .HasColumnType("boolean")
                        .HasColumnName("resisted");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<int>("UrgeIntensity")
                        .HasColumnType("integer")
                        .HasColumnName("urge_intensity");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserId", "AddictionType");

                    b.HasIndex("UserId", "Timestamp");

                    b.ToTable("urge_events", (string)null);
                });

            modelBuilder.Entity("Frank.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("AddictionDuration")
                        .HasColumnType("text")
                        .HasColumnName("addiction_duration");

                    b.Property<string[]>("AddictionTypes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("addiction_types");

                    b.Property<string>("ChangeStage")
                        .HasColumnType("text")
                        .HasColumnName("change_stage");

                    b.Property<string>("CoreMotivation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("core_motivation");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string[]>("EnvironmentRisks")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("environment_risks");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("FutureSelfText")
                        .HasColumnType("text")
                        .HasColumnName("future_self_text");

                    b.Property<string>("HabitDuration")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("habit_duration");

                    b.Property<string>("IdentityFraming")
                        .HasColumnType("text")
                        .HasColumnName("identity_framing");

                    b.Property<string>("PostSlipEmotion")
                        .HasColumnType("text")
                        .HasColumnName("post_slip_emotion");

                    b.Property<string>("PreUrgeDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pre_urge_description");

                    b.Property<string[]>("ReplacementStack")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("replacement_stack");

                    b.Property<string[]>("RiskWindows")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("risk_windows");

                    b.Property<string>("SocialSupportLevel")
                        .HasColumnType("text")
                        .HasColumnName("social_support_level");

                    b.Property<string>("SpecificTriggers")
                        .HasColumnType("text")
                        .HasColumnName("specific_triggers");

                    b.HasKey("UserId");

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("Frank.Domain.Entities.UserSummary", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("AllTime")
                        .HasColumnType("jsonb")
                        .HasColumnName("all_time");

                    b.Property<int>("DailyUrgeCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("daily_urge_count");

                    b.Property<string>("Last30Days")
                        .HasColumnType("jsonb")
                        .HasColumnName("last_30_days");

                    b.Property<string>("Last7Days")
                        .HasColumnType("jsonb")
                        .HasColumnName("last_7_days");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.ToTable("user_summaries", (string)null);
                });

            modelBuilder.Entity("Frank.Domain.Entities.WeeklySummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Observation1")
                        .HasColumnType("text")
                        .HasColumnName("observation_1");

                    b.Property<string>("Observation2")
                        .HasColumnType("text")
                        .HasColumnName("observation_2");

                    b.Property<string>("Observation3")
                        .HasColumnType("text")
                        .HasColumnName("observation_3");

                    b.Property<string>("QuotesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("quotes_json");

                    b.Property<string>("ReflectionQId")
                        .HasColumnType("text")
                        .HasColumnName("reflection_q_id");

                    b.Property<string>("ReflectionText")
                        .HasColumnType("text")
                        .HasColumnName("reflection_text");

                    b.Property<double>("ResistRate")
                        .HasColumnType("double precision")
                        .HasColumnName("resist_rate");

                    b.Property<double?>("ResistRateDelta")
                        .HasColumnType("double precision")
                        .HasColumnName("resist_rate_delta");

                    b.Property<string>("TopHaltRoot")
                        .HasColumnType("text")
                        .HasColumnName("top_halt_root");

                    b.Property<int>("TotalResisted")
                        .HasColumnType("integer")
                        .HasColumnName("total_resisted");

                    b.Property<int>("TotalUrges")
                        .HasColumnType("integer")
                        .HasColumnName("total_urges");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("date")
                        .HasColumnName("week_start");

                    b.Property<string>("WorstDay")
                        .HasColumnType("text")
                        .HasColumnName("worst_day");

                    b.Property<int?>("WorstHour")
                        .HasColumnType("integer")
                        .HasColumnName("worst_hour");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "WeekStart")
                        .IsUnique();

                    b.ToTable("weekly_summaries", (string)null);
                });

            modelBuilder.Entity("Frank.Domain.Entities.Answer", b =>
                {
                    b.HasOne("Frank.Domain.Entities.Question", null)
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Frank.Domain.Entities.ChatSession", "Session")
                        .WithMany("Answers")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Frank.Domain.Entities.ConversationHistory", b =>
                {
                    b.HasOne("Frank.Domain.Entities.ChatSession", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Frank.Domain.Entities.EveningCheckin", b =>
                {
                    b.HasOne("Frank.Domain.Entities.ChatSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Frank.Domain.Entities.UserProfile", "User")
                        .WithMany("EveningCheckins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Frank.Domain.Entities.MiniMirrorEvent", b =>
                {
                    b.HasOne("Frank.Domain.Entities.UserProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Frank.Domain.Entities.MorningCheckin", b =>
                {
                    b.HasOne("Frank.Domain.Entities.ChatSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Frank.Domain.Entities.UserProfile", "User")
                        .WithMany("MorningCheckins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Frank.Domain.Entities.NotificationLog", b =>
                {
                    b.HasOne("Frank.Domain.Entities.UserProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Frank.Domain.Entities.PreUrgeVersion", b =>
                {
                    b.HasOne("Frank.Domain.Entities.UserProfile", "User")
                        .WithMany("PreUrgeVersions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Frank.Domain.Entities.QuestionUsage", b =>
                {
                    b.HasOne("Frank.Domain.Entities.Question", "Question")
                        .WithMany("QuestionUsages")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Frank.Domain.Entities.TapOption", b =>
                {
                    b.HasOne("Frank.Domain.Entities.Question", "Question")
                        .WithMany("TapOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Frank.Domain.Entities.UrgeEvent", b =>
                {
                    b.HasOne("Frank.Domain.Entities.ChatSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Frank.Domain.Entities.UserProfile", "User")
                        .WithMany("UrgeEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Frank.Domain.Entities.UserSummary", b =>
                {
                    b.HasOne("Frank.Domain.Entities.UserProfile", "User")
                        .WithOne("UserSummary")
                        .HasForeignKey("Frank.Domain.Entities.UserSummary", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Frank.Domain.Entities.WeeklySummary", b =>
                {
                    b.HasOne("Frank.Domain.Entities.UserProfile", "User")
                        .WithMany("WeeklySummaries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Frank.Domain.Entities.ChatSession", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Frank.Domain.Entities.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("QuestionUsages");

                    b.Navigation("TapOptions");
                });

            modelBuilder.Entity("Frank.Domain.Entities.UserProfile", b =>
                {
                    b.Navigation("EveningCheckins");

                    b.Navigation("MorningCheckins");

                    b.Navigation("PreUrgeVersions");

                    b.Navigation("UrgeEvents");

                    b.Navigation("UserSummary");

                    b.Navigation("WeeklySummaries");
                });
#pragma warning restore 612, 618
        }
    }
}
